id: AB9782129
title: Prayer for the Long Life of Khandro Tāre Lhamo
type: translation
pechas:
- IA669B7FA
- I28286F27
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:47.762132
  last_modified_at: 2023-01-04 12:49:47.762177
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  IA669B7FA/4924: '4673'
  I28286F27/996C: '4673'
